"""
reporter.py — Consumes agent-reports from Kafka, saves Markdown incident reports to disk.
"""

import json
import os
from datetime import datetime
from confluent_kafka import Consumer
from rich.console import Console
from config import KAFKA_BOOTSTRAP_SERVERS, TOPIC_AGENT_REPORTS

console = Console()
REPORTS_DIR = "reports"


def sanitize_filename(ip: str) -> str:
    return ip.replace(".", "_")


def run():
    os.makedirs(REPORTS_DIR, exist_ok=True)
    consumer = Consumer({
        "bootstrap.servers": KAFKA_BOOTSTRAP_SERVERS,
        "group.id": "netsleuth-reporter",
        "auto.offset.reset": "latest",
    })
    consumer.subscribe([TOPIC_AGENT_REPORTS])
    console.print(f"[bold cyan] Reporter started — consuming '{TOPIC_AGENT_REPORTS}'[/bold cyan]\n")

    try:
        while True:
            msg = consumer.poll(timeout=1.0)
            if msg is None:
                continue
            if msg.error():
                console.print(f"[red]Consumer error: {msg.error()}[/red]")
                continue

            report = json.loads(msg.value().decode("utf-8"))
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            ip_safe = sanitize_filename(report["source_ip"])
            filename = f"{REPORTS_DIR}/incident_{timestamp}_{ip_safe}.md"

            content = f"""#  NetSleuth Incident Report

**Generated:** {report['timestamp']}
**Source IP:** `{report['source_ip']}`
**Host:** `{report['host']}`
**Severity:** `{report['severity'].upper()}`
**Status:** {report['status']}

---

{report['report']}

---
*Generated by NetSleuth — AI-Powered Network Anomaly Detective*
"""
            with open(filename, "w", encoding="utf-8") as f:
                f.write(content)

            console.print(f"[bold green] Saved: {filename}[/bold green]")
            console.print(f"[dim]{report['report'][:300]}...[/dim]\n")

    except KeyboardInterrupt:
        console.print("\n[yellow]Reporter stopped.[/yellow]")
    finally:
        consumer.close()


if __name__ == "__main__":
    run()
